feat: add header
LBokan/smarthome pull request #6
Opened 2022-11-23 13:14 UTC by LBokan

### Description

Added header component

### Type of change

- [x] Feature (introduces new functionality)
- [ ] Bugfix
- [ ] Configuration
- [x] Refactoring (doesn't change functionality, only the code)
- [ ] Style changes (doesn't affect functionality, only the look of the components)

### PR Checklist

- [x] Synced up with latest from the main branch/Code is linted
- [x] Description of the changes has been added (Screenshots/Video)
- [x] Material UI components/constants/hooks have been used wherever possible

> If not explain here

- [x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
- [x] Console has been checked for warnings

#### Screenshots/Video before change

Add screenshots of the changed components here.

#### Screenshots/Video after change

https://user-images.githubusercontent.com/117748123/203555183-bdd484b3-e22a-40d2-9229-ba68c69ded61.mp4

2022-11-23 15:00 UTC, ahodkov requested changes

2022-11-23 15:00 UTC, ahodkov commented on src/components/Header/Header.jsx
> +    <>
Думаю, что это излишне. <Box> это же единственный child здесь

2022-11-23 15:00 UTC, ahodkov commented on src/components/Header/UserInfo.jsx
> +        alt="Ivan Ivanov"
alt="Profile Image"

2022-11-23 15:00 UTC, ahodkov commented on src/components/Header/UserInfo.jsx
> +export const UserInfo = () => {
Наверное лучше добавить сразу параметры и просто его передавать:
`export const UserInfo = ({imageSrc, fullName, title}) => {}`

2022-11-23 15:00 UTC, ahodkov commented on src/components/Header/UserInfo.jsx
> +export const UserInfo = () => {
и добавить PropTypes

2022-11-23 15:00 UTC, ahodkov commented on src/components/RouterLink/RouterLink.jsx
> +export const RouterLink = ({ children, linkPath, stylesObj }) => {
PropTypes

2022-11-23 15:00 UTC, ahodkov commented on src/components/ContentContainer/ContentContainer.jsx
>          flexDirection: 'column',
ContanetContainer тоже добавить PropTypes

2022-11-23 15:00 UTC, ahodkov commented on src/components/ContentWrapper/ContentWrapper.jsx
> +export const ContentWrapper = ({ children, type = 'div', stylesObj = {} }) => {
PropTypes

2022-11-23 15:00 UTC, ahodkov commented on src/components/Header/UserPanel.jsx
> +import SettingsIcon from '@mui/icons-material/Settings';
если в icons-material есть re-импорт в index.js, то есть смысл сделать импорт в одну строчку.
То есть:
`import {NotificationsIcon, SettingsIcon} from '@mui/icons-material'`

2022-11-23 15:03 UTC, ahodkov commented on src/components/Header/UserPanel.jsx
> +import SettingsIcon from '@mui/icons-material/Settings';
https://mui.com/material-ui/icons/#usage option 2

2022-11-23 15:06 UTC, ahodkov commented on src/components/Header/UserInfo.jsx
> +export const UserInfo = () => {
https://reactjs.org/docs/typechecking-with-proptypes.html

2022-11-24 08:05 UTC, LBokan commented on src/components/Header/Header.jsx
> +    <>
Убрала <> и </>
![image](https://user-images.githubusercontent.com/117748123/203726971-6c48e2f7-1598-4f33-9558-bb1c7d3c27e1.png)

2022-11-24 08:07 UTC, LBokan commented on src/components/Header/UserInfo.jsx
> +        alt="Ivan Ivanov"
![image](https://user-images.githubusercontent.com/117748123/203727420-013a5bf6-14d0-429d-8470-8f2eb65bd84e.png)

2022-11-24 08:36 UTC, LBokan commented on src/components/Header/UserInfo.jsx
> +export const UserInfo = () => {
![image](https://user-images.githubusercontent.com/117748123/203732958-209f699a-462a-4d55-863e-466f58f1b58a.png)

2022-11-24 09:22 UTC, LBokan commented on src/components/RouterLink/RouterLink.jsx
> +export const RouterLink = ({ children, linkPath, stylesObj }) => {
![image](https://user-images.githubusercontent.com/117748123/203745982-9ab211b5-8fd0-4625-801b-38f1dea8d44c.png)

2022-11-24 09:24 UTC, LBokan commented on src/components/ContentContainer/ContentContainer.jsx
>          flexDirection: 'column',
![image](https://user-images.githubusercontent.com/117748123/203746520-623784c4-3922-443d-a681-c758201dd6bc.png)

2022-11-24 09:27 UTC, LBokan commented on src/components/ContentWrapper/ContentWrapper.jsx
> +export const ContentWrapper = ({ children, type = 'div', stylesObj = {} }) => {
![image](https://user-images.githubusercontent.com/117748123/203746958-fc798122-1f27-4f15-8201-1df70e329fbe.png)

2022-11-24 09:31 UTC, LBokan commented on src/components/Header/UserPanel.jsx
> +import SettingsIcon from '@mui/icons-material/Settings';
![image](https://user-images.githubusercontent.com/117748123/203747651-61419873-4568-4184-bb43-b00f347474bb.png)
![image](https://user-images.githubusercontent.com/117748123/203747728-507ffd93-2fe6-40ec-b7e4-7acb7f5881f0.png)
![image](https://user-images.githubusercontent.com/117748123/203747977-742b43bd-b1ae-40be-9db2-4904b4d057d7.png)

2022-11-24 09:38 UTC, ahodkov commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack-dev-server",
Можно добавить
"start:prod": "cross-end NODE_ENV=production webpack-dev-server"

2022-11-24 09:38 UTC, ahodkov approved these changes

2022-11-24 09:40 UTC, LBokan commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack-dev-server",
Ок, добавлю в след. PR

2022-11-24 09:40 UTC, merged