feat: add aside, theme mode
LBokan/smarthome pull request #8
Opened 2022-11-25 10:30 UTC by LBokan

### Description

Added aside panel with toggle button and theme mode button

### Type of change

- [x] Feature (introduces new functionality)
- [ ] Bugfix
- [ ] Configuration
- [ ] Refactoring (doesn't change functionality, only the code)
- [ ] Style changes (doesn't affect functionality, only the look of the components)

### PR Checklist

- [x] Synced up with latest from the main branch/Code is linted
- [x] Description of the changes has been added (Screenshots/Video)
- [x] Material UI components/constants/hooks have been used wherever possible

> If not explain here

- [x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
- [x] Console has been checked for warnings

#### Screenshots/Video before change

Add screenshots of the changed components here.

#### Screenshots/Video after change

https://user-images.githubusercontent.com/117748123/203963542-e750f13f-4c73-4346-b3fe-2478becc6556.mp4

2022-11-25 12:15 UTC, ahodkov requested changes
Лучше отказываться от экспериментальных фич: они могут слишком непредсказуемо вести себя на проде. В документации про это написано, так что проблем с этим может быть много

2022-11-25 12:15 UTC, ahodkov commented on src/index.jsx
> +import { Experimental_CssVarsProvider as CssVarsProvider } from '@mui/material/styles';
ThemProvider более стабильный, лучше его использовать

2022-11-25 12:15 UTC, ahodkov commented on src/index.jsx
> -    <ThemeProvider theme={lightTheme}>
Исходя из личного опыта, то theming часто храниться на сервере, в таком случае лучше сделать так:
1. Написать хук, например useDarkMode, так как у нас нет сервера. Будем использовать redux. Для хранения/взаимодействия. Возвращает isDarkModeEnabled, setDarkModeEnable.
2. Добавить сюда этот хук 
3. Использовать <ThemeProvider theme={isDarkModeEnabled ? darkTheme : lightTheme}>

2022-11-25 12:15 UTC, ahodkov commented on src/pages/Landing.jsx
> +      <Aside />
Так, если у нас используется Aside не в одном месте - есть смысл переместить Aside на родителя повыше

2022-11-25 12:15 UTC, ahodkov commented on src/theme/theme.js
> +import { experimental_extendTheme as extendTheme } from '@mui/material/styles';
Лучше удалить этот файл

2022-11-27 10:54 UTC, LBokan commented on src/index.jsx
> +import { Experimental_CssVarsProvider as CssVarsProvider } from '@mui/material/styles';
Вернула его

2022-11-27 11:26 UTC, LBokan commented on src/theme/theme.js
> +import { experimental_extendTheme as extendTheme } from '@mui/material/styles';
Удалила

2022-11-27 11:34 UTC, LBokan commented on src/pages/Landing.jsx
> +      <Aside />
Вынесла в Layout.jsx

2022-11-28 10:35 UTC, ahodkov approved these changes

2022-11-28 10:35 UTC, merged