feat: add device list
LBokan/smarthome pull request #9
Opened 2022-11-29 11:31 UTC by LBokan

### Description

Added device list and item components, import 'moment' and 'chartjs' libraries

### Type of change

- [x] Feature (introduces new functionality)
- [ ] Bugfix
- [ ] Configuration
- [ ] Refactoring (doesn't change functionality, only the code)
- [ ] Style changes (doesn't affect functionality, only the look of the components)

### PR Checklist

- [x] Synced up with latest from the main branch/Code is linted
- [x] Description of the changes has been added (Screenshots/Video)
- [x] Material UI components/constants/hooks have been used wherever possible

> If not explain here

- [x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
- [x] Console has been checked for warnings

#### Screenshots/Video before change

Add screenshots of the changed components here.

#### Screenshots/Video after change

https://user-images.githubusercontent.com/117748123/204517797-aa77fce1-d642-4828-9ab2-4f720400ea28.mp4

![image](https://user-images.githubusercontent.com/117748123/204517807-d2cdb930-6a20-4970-a59e-3826bb959acf.png)

![image](https://user-images.githubusercontent.com/117748123/204517876-0c2e3896-6e4b-444f-83f5-2a2e96ae4bd3.png)

2022-11-29 11:52 UTC, ahodkov requested changes

2022-11-29 11:52 UTC, ahodkov commented on src/components/LogsInfoMenu/LogsInfoMenu.jsx
> +      {!!logsData.issues.length &&
А зачем два отрицания? Если там будет 0, то это же false
Нужно еще добавить вопросительные знаки для того, чтобы избежать undefined

2022-11-29 11:52 UTC, ahodkov commented on src/helpers/chartsHelpers.js
> +  return new Date().toISOString().split('T')[0];
Если используем moment, то явно лучше это убрать

2022-11-29 11:52 UTC, ahodkov commented on src/helpers/chartsHelpers.js
> +export const createWeekLogsQtyArr = (logsArr) => {
кажется, что это лишнее 
Вам же приходят даты, так с ними и надо работать. Там просто надо добавить форматирование

2022-11-29 11:53 UTC, ahodkov commented
Еще в отображении девайсов, лучше убрать скроллинг и показывать больше, если слишком много - добавьте пагинацию

2022-11-29 12:39 UTC, LBokan commented on src/helpers/chartsHelpers.js
> +  return new Date().toISOString().split('T')[0];
Заменила на moment

2022-11-29 14:55 UTC, LBokan commented on src/components/LogsInfoMenu/LogsInfoMenu.jsx
> +      {!!logsData.issues.length &&
Оставила свой вариант

2022-11-29 14:55 UTC, LBokan commented on src/helpers/chartsHelpers.js
> +export const createWeekLogsQtyArr = (logsArr) => {
Убрала

2022-11-30 08:04 UTC, ahodkov approved these changes

2022-11-30 08:05 UTC, merged